### ISSUE TITLE
investigar cálculo da métrica cbo pelo analizo

### ISSUE THREAD

**Issue by joenio** [joenio/dissertacao-ufba-2016#16]
os dados encontrados apontam um comportamento bastante estranho para a métrica cbo calculada pelo analizo, será preciso investivar o cálculo desta métrica uma vez que Ronaldo em seu TCC também sinaliza valores suspeitos para ela:

```
É importante enfatizar que inicialmente a métrica de acoplamento que seria uti-
lizada seria CBO, a fim de comparação com complexidade estrutural apresentados em
trabalhos como o de Terceiro e Chavez (2009). Entretanto, foram encontrados aqui valo-
res muito discrepantes dos valores esperados, divergindo muito dos valores encontrados
por Meirelles (2013), inclusive para o sistema Android, levando então a conclusão de
que algum problema pode ter ocorrido no cálculo da ferramenta. Assim, a métrica de
acoplamento utilizada neste estudo foi a métrica ACC.
```

**Comment by joenio** [comment]
@paulormm o que você acha?

**Comment by paulormm** [comment]
Discordo ;)

Temos que usar o mesmo conceito e fórmula de Terceiro. Entendo que esse comportamento do CBO deve ser externado, discutido e investigado.

**Comment by joenio** [comment]
sim, sim...

mas tô achando que o analizo tá calculando cbo errado :'(

**Comment by paulormm** [comment]
Mas não podemos mudar a métrica de SC agora. Temos que investigar...

**Comment by paulormm** [comment]
para a qualificação, acho que tem que ser CBO \* LCOM.

**Comment by joenio** [comment]
sim, eu entendo, não vamos mudar nada, mas tô desconfiado que os valores estão errados... estou seguindo com CBO e LCOM mesmo.

Valeu!!!

**Comment by paulormm** [comment]
Entendi. Pensei que você queria mudar isso no seu texto agora ;). Vamos investigar mesmo isso no Analizo.

**Comment by joenio** [comment]
estava realmente calculando errado, corrigido, a nova versão 1.19.1 do analizo está ok.
