### ISSUE TITLE
Revisão da Release 2017-05-04

### ISSUE THREAD

**Issue by paulormm** [joenio/dissertacao-ufba-2016#40]
@joenio e @christinaflach : coloquei em minha agenda para revisar a versão/release 2017-05-04 (https://github.com/joenio/dissertacao-ufba-2016/releases/tag/2017-05-04) nesta sexta-feira.

Mando o feedback nesta issue.

**Comment by joenio** [comment]
beleza @paulormm, valeu! conseguiu dar uma olhada no texto?

**Comment by paulormm** [comment]
Olhei, mas preciso marcar os pontos de revisão, o que vou fazer na quarta-feira. Eu queria mesmo ler uma versão com o Capítulo 4.

**Comment by joenio** [comment]
massa, valeu! bem... o capítulo 4 não tenho ainda uma versão, subi uns commits com algum conteúdo, mas ainda está desestruturado...

**Comment by paulormm** [comment]
Segue o PDF comentado. Qualquer coisa, podemos nos falar ao final da nossa outra conversar, nesta quinta-feira.

Em suma, o que está escrito está bom e adequado. Precisamos de mais para o texto ter um corpo mesmo.

[dissertacao-release04-05-17_Rev-Paulo.pdf](https://github.com/joenio/dissertacao-ufba-2016/files/991299/dissertacao-release04-05-17_Rev-Paulo.pdf)

**Comment by joenio** [comment]
considerações aplicadas no commit 4677f9c9b0fc5975324008a9abb02b34e29ec97b

pendente: encontrar um termo mais adequado para "disponibilidade"
