### ISSUE TITLE
dar mais corpo ao capítulo 3 de revisão estruturada

### ISSUE THREAD

**Issue by joenio** [joenio/dissertacao-ufba-2016#41]
"Precisamos de mais para o texto ter um corpo mesmo." -- paulo

desdobramento da issue #40

**Comment by joenio** [comment]
usar referências sobre revisão e mapeamento sistemático para melhorar o texto da revisão estruturada, talvez adotar alguns protocolos e práticas adaptando ao que já foi feito, não irei refazer a revisão apenas descrever melhor seu planejamento, execução e resultados:

* http://wiki.dcc.ufba.br/Aside/RelatorioDeAndamentoOrientacao2014JoenioCosta1
* http://wiki.dcc.ufba.br/Aside/RelatorioDeAndamentoOrientacao2014JoenioCosta0
* http://wiki.dcc.ufba.br/Aside/RelatorioDeAndamentoOrientacao2014JoenioCosta2
* http://wiki.dcc.ufba.br/Aside/RelatorioDeAndamentoOrientacao2014JoenioCosta3
* http://wiki.dcc.ufba.br/Aside/RelatorioDeAndamentoOrientacao2014JoenioCosta4
* http://wiki.dcc.ufba.br/Aside/RelatorioDeAndamentoOrientacao2014JoenioCosta5

**Comment by paulormm** [comment]
Entendeu errado. O que está feito está bom, precisamos dos outros capítulos. Não precisa voltar para a revisão não. O quanto antes será bom ter o Capítulo 4.

**Comment by joenio** [comment]
a revisão de literatura (revisão estruturada) foi apresentada no capítulo 3 (estudo1)
