### ISSUE TITLE
o termo disponibilidade não está bom

### ISSUE THREAD

**Issue by joenio** [joenio/dissertacao-ufba-2016#42]
desdobramento da issue #40

**Comment by joenio** [comment]
Usar o mesmo termo, "sustainability", utilizado no manifesto "Engineering Academic Software (Dagstuhl Perspectives Workshop 16252)":

By “sustainability” we mean the capacity to endure. We define software as sustainable if it will continue to be available in the future, on new platforms, and meet new needs.

**Comment by paulormm** [comment]
Parece bom sim.
